const express = require('express')
const router = express.Router()
const userSignupController = require('../controller/user/userSignup')
const userSigninController = require('../controller/user/userSignin')
const userDetailController = require('../controller/user/userDetail')
const authToken = require('../middleware/authtoken')
const LogoutCOntroller = require('../controller/user/userLogout');
const allUsersController = require('../controller/user/allUser')
const updateUserController = require('../controller/user/updateUser')
const productController = require('../controller/product/uplaodProduct')
const getproductController = require('../controller/product/getProduct')
const editproductController = require('../controller/product/editProduct')
const getProductCategoryController = require('../controller/product/getCategory')
const getcategorywiseController = require('../controller/product/getCategorywiseproduct')
const adminsignupController = require('../controller/aadminpannel/AdminSignup')
const adminsigninController = require('../controller/aadminpannel/AdminSignin')
const adminuserdetailController = require('../controller/aadminpannel/Adminuserdetail')
const adminauthtoken  = require('../middleware/adminauthToken')
const adminLogoutCOntroller = require('../controller/aadminpannel/AdminLogout')
const productdetailController = require('../controller/product/getProductDetails')
const addtocartControoller = require('../controller/user/AddtoCart')
const CountAddtocartController = require('../controller/user/CountAddtoCart')
const AddtoviewCart = require('../controller/user/AddtoviewCart')
const UpdateAddtoCart = require('../controller/user/UpdateAddtoCart')
const DeleteAddtoCart = require('../controller/user/DeleteAddtoCart')
const DeleteProductFromDb = require('../controller/product/Deleteproductfromdb')
const SearchProductController = require('../controller/product/SearchProduct')
const FilterProductController = require('../controller/product/FilterProduct')
const PaymentController = require('../controller/order/PaymentController')
const webhook = require('../controller/order/webhook')
const orderController = require('../controller/order/OrderController')
router.post("/signup" , userSignupController)
router.post("/signin" , userSigninController)
router.get("/userdetail" ,authToken ,userDetailController)
router.get("/logout" , LogoutCOntroller)
router.get("/alluser" , authToken, allUsersController)
router.post("/update" ,authToken , updateUserController)
router.post("/productdata" ,authToken, productController)
router.get("/getproduct" , getproductController)
router.post("/edit" ,authToken ,editproductController)
router.get("/getcategory" , getProductCategoryController)
router.post("/getcategorywise" ,  getcategorywiseController);
router.post("/adminsignup", adminsignupController)
router.post("/adminsignin" , adminsigninController)
router.get("/adminuserdetail" ,adminauthtoken , adminuserdetailController )
router.get("/adminlogout" , adminLogoutCOntroller)
router.post("/productdetail" ,productdetailController)
router.post("/addtocart" ,authToken, addtocartControoller)
router.get("/count" , authToken , CountAddtocartController)
router.get("/view" , authToken ,AddtoviewCart)
router.post("/updatecart"  , UpdateAddtoCart)
router.post("/deletecart" , authToken , DeleteAddtoCart)
router.post("/deleteprod" ,adminauthtoken  ,DeleteProductFromDb)
router.get("/searchproduct" ,SearchProductController )
router.post("/filterprod" , FilterProductController)

//payment order
router.post('/checkout',authToken , PaymentController)
router.post('/webhook' , webhook) //api/webhook
router.get("/orderlist" , authToken , orderController)

module.exports = router